---
Name: myproject
---
StaffPage:
  extensions:
    - StaffPageExtension
StaffHolderPage:
  extensions:
    - StaffHolderPageExtension
StaffPageController:
  extensions:
    - StaffPageControllerExtension
StaffHolderPageController:
  extensions:
    - StaffHolderPageControllerExtension
StaffTeam:
  extensions:
    - StaffTeamExtension
SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    - UserDefinedFormExtension
Member:
  extensions:
    - MemberExtension
